# Generated by Django 2.2 on 2019-04-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y_point', models.FloatField(blank=True, default=None, null=True)),
                ('x_point', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
