# Generated by Django 2.2 on 2019-04-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graoh', '0002_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
