# Generated by Django 2.2 on 2019-04-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graoh', '0003_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphMoEs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_req', models.FloatField(blank=True, default=None, null=True)),
                ('est_oper_equi', models.CharField(max_length=10)),
                ('mes', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
