# Generated by Django 2.2 on 2019-04-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graoh', '0004_auto_20190425_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GraohGraphmoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_req', models.FloatField(blank=True, null=True)),
                ('est_oper_equi', models.CharField(max_length=10)),
                ('mes', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'graoh_graphmoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
            options={
                'db_table': 'tblPoint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbltmpcorrect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_docu', models.CharField(blank=True, max_length=15, null=True)),
                ('num_ifal', models.CharField(blank=True, max_length=25, null=True)),
                ('desc_repa_emis_ifal', models.CharField(blank=True, max_length=80, null=True)),
                ('desc_fami', models.CharField(blank=True, max_length=40, null=True)),
                ('desc_sist', models.CharField(blank=True, max_length=60, null=True)),
                ('desc_equi', models.CharField(blank=True, max_length=120, null=True)),
                ('desc_depa_emis_ifal', models.CharField(blank=True, max_length=70, null=True)),
                ('desc_depa_ejec_ifal', models.CharField(blank=True, max_length=50, null=True)),
                ('dias_tran_ulmo_ifal', models.IntegerField(blank=True, null=True)),
                ('fech_ing_ifal', models.DateField(blank=True, null=True)),
                ('mes_ing_ifal', models.CharField(blank=True, max_length=25, null=True)),
                ('desc_esta_ifal', models.CharField(blank=True, max_length=25, null=True)),
                ('fech_cier_ifal', models.DateField(blank=True, null=True)),
                ('desc_falla_ifal', models.CharField(blank=True, max_length=225, null=True)),
                ('desc_causa_ifal', models.CharField(blank=True, max_length=275, null=True)),
                ('desc_solu_ifal', models.CharField(blank=True, max_length=225, null=True)),
                ('tipo_falla', models.CharField(blank=True, max_length=50, null=True)),
                ('esta_oper_unid', models.CharField(blank=True, max_length=45, null=True)),
                ('esta_porc_unid', models.CharField(blank=True, max_length=25, null=True)),
                ('esta_oper_sist', models.CharField(blank=True, max_length=25, null=True)),
                ('esta_porc_sist', models.CharField(blank=True, max_length=25, null=True)),
                ('esta_oper_equi', models.CharField(blank=True, max_length=25, null=True)),
                ('esta_porc_equi', models.CharField(blank=True, max_length=25, null=True)),
                ('nume_insp', models.CharField(blank=True, max_length=25, null=True)),
                ('desc_falla_insp', models.CharField(blank=True, max_length=225, null=True)),
                ('desc_causa_insp', models.CharField(blank=True, max_length=225, null=True)),
                ('num_ortr', models.CharField(blank=True, max_length=25, null=True)),
                ('desc_ortr', models.CharField(blank=True, max_length=225, null=True)),
                ('componente', models.CharField(blank=True, max_length=40, null=True)),
                ('fech_ingr_ortr', models.DateField(blank=True, null=True)),
                ('mes_ingr_ortr', models.CharField(blank=True, max_length=25, null=True)),
                ('desc_esta_ortr', models.CharField(blank=True, max_length=25, null=True)),
                ('desc_depa_emis_ortr', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_depa_ejec_ortr', models.CharField(blank=True, max_length=200, null=True)),
                ('fech_cierre_ortr', models.DateField(blank=True, null=True)),
                ('depa_gene_reque', models.CharField(blank=True, max_length=25, null=True)),
                ('nume_reque', models.CharField(blank=True, max_length=25, null=True)),
                ('monto_reque', models.FloatField(blank=True, null=True)),
                ('desc_esta_reque', models.CharField(blank=True, max_length=25, null=True)),
                ('fech_regi_reque', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblTmpCorrect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbltmpprevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_docu', models.CharField(blank=True, max_length=15, null=True)),
                ('num_ifal', models.CharField(blank=True, max_length=25, null=True)),
                ('desc_repa_emis_ifal', models.CharField(blank=True, max_length=80, null=True)),
                ('desc_fami', models.CharField(blank=True, max_length=40, null=True)),
                ('desc_sist', models.CharField(blank=True, max_length=60, null=True)),
                ('desc_equi', models.CharField(blank=True, max_length=120, null=True)),
                ('desc_depa_emis_ifal', models.CharField(blank=True, max_length=70, null=True)),
                ('desc_depa_ejec_ifal', models.CharField(blank=True, max_length=50, null=True)),
                ('dias_tran_ulmo_ifal', models.IntegerField(blank=True, null=True)),
                ('fech_ing_ifal', models.DateField(blank=True, null=True)),
                ('mes_ing_ifal', models.CharField(blank=True, max_length=25, null=True)),
                ('desc_esta_ifal', models.CharField(blank=True, max_length=25, null=True)),
                ('fech_cier_ifal', models.DateField(blank=True, null=True)),
                ('desc_falla_ifal', models.CharField(blank=True, max_length=225, null=True)),
                ('desc_causa_ifal', models.CharField(blank=True, max_length=275, null=True)),
                ('desc_solu_ifal', models.CharField(blank=True, max_length=225, null=True)),
                ('tipo_falla', models.CharField(blank=True, max_length=50, null=True)),
                ('esta_oper_unid', models.CharField(blank=True, max_length=45, null=True)),
                ('esta_porc_unid', models.CharField(blank=True, max_length=25, null=True)),
                ('esta_oper_sist', models.CharField(blank=True, max_length=25, null=True)),
                ('esta_porc_sist', models.CharField(blank=True, max_length=25, null=True)),
                ('esta_oper_equi', models.CharField(blank=True, max_length=25, null=True)),
                ('esta_porc_equi', models.CharField(blank=True, max_length=25, null=True)),
                ('nume_insp', models.CharField(blank=True, max_length=25, null=True)),
                ('desc_falla_insp', models.CharField(blank=True, max_length=225, null=True)),
                ('desc_causa_insp', models.CharField(blank=True, max_length=225, null=True)),
                ('num_ortr', models.CharField(blank=True, max_length=25, null=True)),
                ('desc_ortr', models.CharField(blank=True, max_length=225, null=True)),
                ('componente', models.CharField(blank=True, max_length=40, null=True)),
                ('fech_ingr_ortr', models.DateField(blank=True, null=True)),
                ('mes_ingr_ortr', models.CharField(blank=True, max_length=25, null=True)),
                ('desc_esta_ortr', models.CharField(blank=True, max_length=25, null=True)),
                ('desc_depa_emis_ortr', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_depa_ejec_ortr', models.CharField(blank=True, max_length=200, null=True)),
                ('fech_cierre_ortr', models.DateField(blank=True, null=True)),
                ('depa_gene_reque', models.CharField(blank=True, max_length=25, null=True)),
                ('nume_reque', models.CharField(blank=True, max_length=25, null=True)),
                ('monto_reque', models.FloatField(blank=True, null=True)),
                ('desc_esta_reque', models.CharField(blank=True, max_length=25, null=True)),
                ('fech_regi_reque', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblTmpPrevent',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='GraphMoEs',
        ),
    ]
